- functions.php
- includes/theme-images.php
This will help declutter the default editing experience until we're sure that we're introducing images of different sizes.
> [PR] Disable background and thumbnail images on posts and pages

- css/01-layout.css
- css/02-typography.css
- style-guide/home.html
- style.css
- style for special homepage typography
- initial design for content syndicate cards
- `home.html` styleguide content added
> Initial styles for Internal home, including card styles

- css/00-banner.css
- css/01-layout.css
- css/02-typography.css
- functions.php
- package.json
- style-guide/home.html
- style.css
- style for a single feature through `content-syndicate` for the home page
- add content to `home.html` style guide - no template changes needed
> Style top home feature story

- css/01-layout.css
- style.css
These can be seen in the mockups for the home page and main section pages.
> [PR] Add styles for section dividers

- css/01-layout.css
- style-guide/home.html
- style.css
- use `columns` for layout of stories on homepage
- `.main-header` set to `display: none;` on `.single-post`
> Change HP story list layout from `grid` to `columns`

- css/01-layout.css
- css/02-typography.css
- functions.php
- includes/mailchimp.php
- style-guide/home.html
- style.css
- styles for `inputs`
- layout for `top-four` section
- *note* MailChimp code for signup
> Style button, sign up form, and `top-four` article section

- css/01-layout.css
- css/02-typography.css
- style-guide/category.html
- style-guide/home.html
- style-guide/post.html
- style.css
- add `.site-header` to template (outside of `main`)
-- no `.site-header` currently on `.home`
- revised `svg` for site logo
> Update structure and style for headers.

- css/01-layout.css
- css/02-typography.css
- css/03-iconography.css
- style-guide/category.html
- style-guide/home.html
- style.css
- remove `.content-syndicate...` mark up to using `.deck` as a wrapper and `.card` as an item.
- change references of `.hentry` to `main`
> convert markup and style to using `.deck` and `.card`

- css/01-layout.css
- css/02-typography.css
- css/03-iconography.css
- style-guide/category.html
- style.css
- get stylesheet to match HTML class name -- all should have `.card-date`
- update HTML for adjusted card HTML structure
- Enlarge the text for the .`excerpt` slightly
> Card markup and style adjustments

- css/02-typography.css
- style-guide/category.html
- style-guide/home.html
- style.css
- In `category.html` remove the class `.top-four` and add `.bottom-divider` to the same section.
- On `home.html` add `.bottom-divider` to `.news-features` section.
- Update `span.card-date` to `div.card-date`
> Class additions and small style changes

- css/02-typography.css
- style.css
See https://trello.com/c/gGYfu3o9/67-newsletter-subscription-form-needs-work-on-mobile
> [PR] Add responsive styles to the newsletter subscription form

- includes/class-page-curation-customizer-control.php
- includes/page-curation.php
* Empty categories should appear
* Deleted categories should not appear
> [PR] Handle empty and deleted categories in home page curator

- css/01-layout.css
- css/02-typography.css
- style.css
- adjust layout of home page features and good to know section to a a four-column grid
- reduce size of header elements
- reduce white space on post pages
> Post launch style adjustments

- category.php
- css/00-banner.css
- functions.php
- package-lock.json
- package.json
- style.css
Fixes an issue where categories that do not have a featured story would not trigger various display types in the page.
> [PR] Fix bug in category output

- css/02-typography.css
- style.css
- Deepened footer link color `#686868`
- Added `border-bottom` for footer link `:hover`
> Adjusted color of category links in footer to meet accessibility

- css/02-typography.css
- style.css
Changes from #777 (4.48:1) to #767676 (4.54:1)
> [PR] Update description text to be accessible

- css/01-layout.css
- css/02-typography.css
- style.css
> [PR] Fix a couple mobile styles for Announcement views

- css/00-banner.css
- front-page.php
- functions.php
- package-lock.json
- package.json
- style-guide/home.html
This will apply the gray bottom divider.
> Add `bottom-divider` to the *second*  `section.news-features` on home

- css/00-banner.css
- css/01-layout.css
- functions.php
- package-lock.json
- package.json
- style.css
> Fix bug in IE11 home page layout

- index.php
- parts/card-content.php
This provides basic river views for archives other than Categories and Announcements, per an in-person discussion with @slocker3 and Dave.
> [PR] Archive template

- css/01-layout.css
- css/02-typography.css
- style-guide/home.html
- style.css
- Introduce events style and markup for home page
*Note:* IE 11 needs work, more than what was just added
> Initial styles and markup for events on new Insider

- css/01-layout.css
- style.css
Otherwise it's just a bit off. :)
> [PR] Match font size with margin on multi-category cards

- css/00-banner.css
- front-page.php
- functions.php
- package-lock.json
- package.json
- style.css
* Remove gray background
* Show 3 events instead of 4
* Move link to a button below the events
> [PR] Adjust events template on front page

- css/00-banner.css
- functions.php
- package-lock.json
- package.json
- style.css
Removal of the `Read more` tag has evidently presented too much of a disruption to the workflow of the news team.
> [PR] Restore the `Read more` tag

- css/01-layout.css
- style.css
added styling for blockquotes to be used as pull quotes on pages
> 0.11.5 WSU News Theme

- css/00-banner.css
- front-page.php
- functions.php
- package-lock.json
- package.json
- style.css
Linking code to new MailChimp signup form. Form is then attached to a
new MailChimp list.
@philcable #reviewmerge?
> v0.11.5-New MailChimp List

- css/01-layout.css
- css/02-typography.css
Tweaking padding/margins and adding media queries to block quotes,
fixing some square ender style issues, and adding byline styles for
possible use.
> Blockquote, Square Ender, and Byline Styles

- style.css
Redoing some updates tried on a previous attempt to correct compiler
CSS issues.
> Blockquote, Byline, and Ender Styles

- css/00-banner.css
- css/02-typography.css
- style.css
@jbickelhaupt made some minor CSS changes and I went ahead and recompiled the css for him. The version number needed to be updated in `00-banner.css` and recompiled, so I went ahead and did that as well. 
I think travis was running the grunt compiling before, but since its been down, i'm running it manually for Jon's changes to get them in sooner.
> Updating byline to display:flex and adding quote class to paragraphs

- parts/share-tools.php
added icon to posts for sharing stories via email
> Added email share icon
